{% set name = "dynaphopy" %}
{% set version = "1.16.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c8526b19d6afe5e27b205f01e1f8f5731a96a33e4b4829d3eb91cb8a841d416
  patches: 
    - compiler.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win or py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - phonopy
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib

test:
  imports:
    - dynaphopy

about:
  home: http://abelcarreras.github.io/DynaPhoPy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Phonon Analysis from Molecular Dynamics Data'

  description: |
    Software to calculate crystal microscopic anharmonic properties 
    from molecular dynamics (MD) using the normal-mode-decomposition 
    technique. These properties include the phonon frequency shifts and 
    linewidths, as well as the renormalized force constanst and thermal 
    properties by using quasiparticle theory. This code includes 
    interfaces for MD outputs from VASP and LAMMPS. PHONOPY code is used 
    to obtain harmonic phonon modes.
  doc_url: http://abelcarreras.github.io/DynaPhoPy/
  dev_url: https://github.com/abelcarreras/DynaPhoPy

extra:
  recipe-maintainers:
    - jan-janssen
