{% set name = "dynaphopy" %}
{% set version = "1.17.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb69c0faf3f7e7ce3f9d22f386bc978cf22b85a24b8353d8d67594a85e540f1b
  patches:
    - compiler.patch
    - setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - pip
    - phonopy
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - dynaphopy
  commands:
    - pip check

about:
  home: http://abelcarreras.github.io/DynaPhoPy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Phonon Analysis from Molecular Dynamics Data

  description: |
    Software to calculate crystal microscopic anharmonic properties 
    from molecular dynamics (MD) using the normal-mode-decomposition 
    technique. These properties include the phonon frequency shifts and 
    linewidths, as well as the renormalized force constanst and thermal 
    properties by using quasiparticle theory. This code includes 
    interfaces for MD outputs from VASP and LAMMPS. PHONOPY code is used 
    to obtain harmonic phonon modes.
  doc_url: http://abelcarreras.github.io/DynaPhoPy/
  dev_url: https://github.com/abelcarreras/DynaPhoPy

extra:
  recipe-maintainers:
    - jan-janssen
