travis:
  secure:
    BINSTAR_TOKEN: Qc7NJdelkapesQxP9wV5vyBU2fuSlO3qUMiLdlr5uBzmhhEgzfM++3qB9yVc9iaOO4qKnIGTBXWG2IpxnEqDlcNaXjfPbgaGoTBsDRqeM9662rolYNHUwIhoNu5qbc8Ox68+/O010bHsctummcyNjPyOAfdwSsNnilrkINYfgyqzMEqAwGMtnD7rk+E8SYlyWTqCExfiXZ4wBrrHYpXM97o+R1ajOeNRK7295wgMx6F8uv6oXEbr3E9lEXaRI4zotQwa63aVuYNJP1okekICztGN06RQc1JytSle+5n0WMO64YUOa+o9vA0TVwYBUY4ltNJL1mXIeIgGMoHkDs4zGv+XRz/T3GKKAq1uuim2PEQMB8OD2ZNL0unBNrgGAqhPZ/vBS+T8HmXivv/pPCIZ5f4tynJIWSZpIEACaDmNIbsRMCoiWjZyJ+CQ5nX79nyfbFsg4DWlGGJzAmzWUpaq4XzuwwMdhh6h+18G1SBELHoAoVIG4dQbvcbtG337mAQcxTdx1Wx+XbMVkhYRazA1f9wX1rETW3ooeUGRB5fWlSN8vnxV+5XYV8GHGwQYiu4+XhjKPqyngEklAR6fMDf2+hQT045S7Ch1y1NGkVsBsJA3mljw6pfomDnhtl9t5qrMn49bNGqyMU/tNQbnpJ2MdOzdSHreS5ypA2suD35GQDY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
